server:
  port: 8082 

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
      - AuthenticationFilter
      routes:
        - id: users-service
          uri: lb://users-service
          predicates:
            - Path=/api/v1/users/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders/**
        - id: catalog-service
          uri: lb://catalog-service
          predicates:
          - Path=/api/v1/products/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
